### ISSUE TITLE
Automate deployment of images to Kubernetes

### ISSUE THREAD

**Issue by jonrkarr** [biosimulations/Biosimulations#1571]
- [ ] Create GCloud user and key
- [ ] Save email and key for GCloud user to GitHub secrets. Overwrite the existing secrets; they're just place holders.
  - `GCLOUD_EMAIL`
  - `GCLOUD_KEY`
- [ ] Uncomment last list of `biosimulations/tools/docker-build`

**Comment by bilalshaikh42** [comment]
I have run into the docker hub issue as well previously if I manually pushed images. I was not aware that we are pushing images from actions however (unless this was recently added in). If we are, they should be going to the GHCR not dockerhub. 
We can create the docker images and update them in the repository. 

The update for the deployment needs to be handled by the deployment repository to keep it in sync with the rest of the configuration. Restarting the app automatically will work for most cases, but not if any of the other components in the deployment repository have also changed.

**Comment by jonrkarr** [comment]
Until this weekend, the GitHub action was not correctly building all images. It was just building one image. I fixed this. I also parallelized the GitHub action to speed up building images for all of the apps (and linting and testing the apps).

It would be helpful to understand how the deployment works because running the kuberctl control command does not deploy the latest version of the apps. From what I can tell, the deployment relies on the images in Docker Hub. The problem is that Docker Hub's build queue has been as long as 1.5 days recently. This is too long to check that changes are implemented correctly. To speed this up, I started pushing images to both GHCR and Docker Hub. Right now, the images pushed to Docker Hub will be overwritten when Docker Hub builds the image and applies the same label, but this will happen hours to days later.

Updating the deployment can be in an action in the appropriate repository. This can be triggered from actions on the Biosimulations repository.

**Comment by bilalshaikh42** [comment]
I see. The docker build action had not been completed yet. I assume that it was using the cache from previous builds which was causing the same image to be built on a loop. This was not being pushed to docker hub however, as I had not yet fixed the cache issue. 
Dockerhub is building the images independently. This can be turned off now since the actions will update the images as needed. I had been running the apps locally to prevent the queuing issue. A build is triggered by every push to dev, so can be come quite large when pushing without pull requests, or merging in several dependency updates. The few times I encountered this, I was able to push manually as a temporary workaround.

The deployment uses the latest image tagged with dev that is on docker-hub. I presume the issues that you were running into was due to the queuing. Otherwise, the deployment should be rather quick once a image is built.
